# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghissues < Formula
  desc "Browse GitHub issues in your terminal"
  homepage "https://github.com/ssshhhooota/ghissues"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ssshhhooota/ghissues/releases/download/v0.1.0/ghissues_0.1.0_darwin_amd64.tar.gz"
      sha256 "e8abf90744891465e1aa71fb27489b716a1be9563caddbddc86056e70fea3a2f"

      define_method(:install) do
        bin.install "ghissues"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ssshhhooota/ghissues/releases/download/v0.1.0/ghissues_0.1.0_darwin_arm64.tar.gz"
      sha256 "bbd50b3601ef37911f75fd8a4806fc6ee84f08fca17b295fd8b60cd33717f1dc"

      define_method(:install) do
        bin.install "ghissues"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ssshhhooota/ghissues/releases/download/v0.1.0/ghissues_0.1.0_linux_amd64.tar.gz"
      sha256 "e8fb666c36a6636e13b9f906e8e401218e3da9c9f406691c9e89ddf02e7ea08a"
      define_method(:install) do
        bin.install "ghissues"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ssshhhooota/ghissues/releases/download/v0.1.0/ghissues_0.1.0_linux_arm64.tar.gz"
      sha256 "2503b6dd1e8002d9e866822ea8230ca35819eec868d8423fef2ee3cfcb5574f3"
      define_method(:install) do
        bin.install "ghissues"
      end
    end
  end

  test do
    assert_predicate bin/"ghissues", :exist?
  end
end
