# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mochisu < Formula
  desc "Browse GitHub issues in your terminal"
  homepage "https://github.com/ssshhhooota/mochisu"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ssshhhooota/mochisu/releases/download/v0.2.0/mochisu_0.2.0_darwin_amd64.tar.gz"
      sha256 "3cc2a05244e05afd975b7e3796c9cf3eee7e23f3c2415f88d11e0aa4225d92db"

      define_method(:install) do
        bin.install "mochisu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ssshhhooota/mochisu/releases/download/v0.2.0/mochisu_0.2.0_darwin_arm64.tar.gz"
      sha256 "dcbb0e314d636f2df40c53de00986741c414203d643cb7081c7859f8ba4563f8"

      define_method(:install) do
        bin.install "mochisu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ssshhhooota/mochisu/releases/download/v0.2.0/mochisu_0.2.0_linux_amd64.tar.gz"
      sha256 "24a950f46412591eebbab24da231844de31c21540f0b9b8a2c657e907bccb2e9"
      define_method(:install) do
        bin.install "mochisu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ssshhhooota/mochisu/releases/download/v0.2.0/mochisu_0.2.0_linux_arm64.tar.gz"
      sha256 "1752075c1b2cad1ca415d1c8ced3daa33d0ae582c1db5eec4a70aea003f3c362"
      define_method(:install) do
        bin.install "mochisu"
      end
    end
  end

  test do
    assert_predicate bin/"mochisu", :exist?
  end
end
